include "meta_flb.fbs";

table  ClientConnectRequest {
    fd:int;
}

table ClientConnectReply {
    capacity:int;
}

table DBCreateRequest {
   cnt_id:ContentIDRequest;
   cnt_desc:ContentDescRequest;
   sto_desc:StoreDescRequest;
   file_path_list:FilePathListRequest;
}

table DataBoxMetaRequest {
    id: int;
    step_count: int;
    var_count: int;
    var_len: int;
    vldesc: VLDescRequest;
    filled: bool;
}

table DBCreateReply {
    db_meta: DataBoxMetaRequest;
}

table DBgetRequest {
    cnt_id:ContentIDRequest;
    timeout:long;
}

table DBgetReply {
    ip:string;
    port:int;
}

table DBcontainRequest {
    cnt_id:ContentIDRequest;
}

table DBcontainReply {
    is_contain:bool;
}

table DBReleaseRequest {
    cnt_id:ContentIDRequest;
}

table DBReleaseReply {
    is_release: bool;
}

table DBDeleteRequest {
    cnt_id:ContentIDRequest;
}

table DBDeleteReply {
    is_delete:bool;
}

table GetContentIDRequest {
    db_id:ulong;
}

table GetContentIDReply {
    cnt_id:ContentIDRequest;
}




