// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DBFLB_H_
#define FLATBUFFERS_GENERATED_DBFLB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "meta_flb_generated.h"

struct ClientConnectRequest;
struct ClientConnectRequestBuilder;

struct ClientConnectReply;
struct ClientConnectReplyBuilder;

struct DBCreateRequest;
struct DBCreateRequestBuilder;

struct DataBoxMetaRequest;
struct DataBoxMetaRequestBuilder;

struct DBCreateReply;
struct DBCreateReplyBuilder;

struct DBgetRequest;
struct DBgetRequestBuilder;

struct DBgetReply;
struct DBgetReplyBuilder;

struct DBcontainRequest;
struct DBcontainRequestBuilder;

struct DBcontainReply;
struct DBcontainReplyBuilder;

struct DBReleaseRequest;
struct DBReleaseRequestBuilder;

struct DBReleaseReply;
struct DBReleaseReplyBuilder;

struct DBDeleteRequest;
struct DBDeleteRequestBuilder;

struct DBDeleteReply;
struct DBDeleteReplyBuilder;

struct GetContentIDRequest;
struct GetContentIDRequestBuilder;

struct GetContentIDReply;
struct GetContentIDReplyBuilder;

struct ClientConnectRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientConnectRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FD = 4
  };
  int32_t fd() const {
    return GetField<int32_t>(VT_FD, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_FD, 4) &&
           verifier.EndTable();
  }
};

struct ClientConnectRequestBuilder {
  typedef ClientConnectRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fd(int32_t fd) {
    fbb_.AddElement<int32_t>(ClientConnectRequest::VT_FD, fd, 0);
  }
  explicit ClientConnectRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientConnectRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientConnectRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientConnectRequest> CreateClientConnectRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t fd = 0) {
  ClientConnectRequestBuilder builder_(_fbb);
  builder_.add_fd(fd);
  return builder_.Finish();
}

struct ClientConnectReply FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientConnectReplyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CAPACITY = 4
  };
  int32_t capacity() const {
    return GetField<int32_t>(VT_CAPACITY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_CAPACITY, 4) &&
           verifier.EndTable();
  }
};

struct ClientConnectReplyBuilder {
  typedef ClientConnectReply Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_capacity(int32_t capacity) {
    fbb_.AddElement<int32_t>(ClientConnectReply::VT_CAPACITY, capacity, 0);
  }
  explicit ClientConnectReplyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientConnectReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientConnectReply>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientConnectReply> CreateClientConnectReply(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t capacity = 0) {
  ClientConnectReplyBuilder builder_(_fbb);
  builder_.add_capacity(capacity);
  return builder_.Finish();
}

struct DBCreateRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBCreateRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CNT_ID = 4,
    VT_CNT_DESC = 6,
    VT_STO_DESC = 8,
    VT_FILE_PATH_LIST = 10
  };
  const ContentIDRequest *cnt_id() const {
    return GetPointer<const ContentIDRequest *>(VT_CNT_ID);
  }
  const ContentDescRequest *cnt_desc() const {
    return GetPointer<const ContentDescRequest *>(VT_CNT_DESC);
  }
  const StoreDescRequest *sto_desc() const {
    return GetPointer<const StoreDescRequest *>(VT_STO_DESC);
  }
  const FilePathListRequest *file_path_list() const {
    return GetPointer<const FilePathListRequest *>(VT_FILE_PATH_LIST);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CNT_ID) &&
           verifier.VerifyTable(cnt_id()) &&
           VerifyOffset(verifier, VT_CNT_DESC) &&
           verifier.VerifyTable(cnt_desc()) &&
           VerifyOffset(verifier, VT_STO_DESC) &&
           verifier.VerifyTable(sto_desc()) &&
           VerifyOffset(verifier, VT_FILE_PATH_LIST) &&
           verifier.VerifyTable(file_path_list()) &&
           verifier.EndTable();
  }
};

struct DBCreateRequestBuilder {
  typedef DBCreateRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cnt_id(::flatbuffers::Offset<ContentIDRequest> cnt_id) {
    fbb_.AddOffset(DBCreateRequest::VT_CNT_ID, cnt_id);
  }
  void add_cnt_desc(::flatbuffers::Offset<ContentDescRequest> cnt_desc) {
    fbb_.AddOffset(DBCreateRequest::VT_CNT_DESC, cnt_desc);
  }
  void add_sto_desc(::flatbuffers::Offset<StoreDescRequest> sto_desc) {
    fbb_.AddOffset(DBCreateRequest::VT_STO_DESC, sto_desc);
  }
  void add_file_path_list(::flatbuffers::Offset<FilePathListRequest> file_path_list) {
    fbb_.AddOffset(DBCreateRequest::VT_FILE_PATH_LIST, file_path_list);
  }
  explicit DBCreateRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBCreateRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBCreateRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBCreateRequest> CreateDBCreateRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ContentIDRequest> cnt_id = 0,
    ::flatbuffers::Offset<ContentDescRequest> cnt_desc = 0,
    ::flatbuffers::Offset<StoreDescRequest> sto_desc = 0,
    ::flatbuffers::Offset<FilePathListRequest> file_path_list = 0) {
  DBCreateRequestBuilder builder_(_fbb);
  builder_.add_file_path_list(file_path_list);
  builder_.add_sto_desc(sto_desc);
  builder_.add_cnt_desc(cnt_desc);
  builder_.add_cnt_id(cnt_id);
  return builder_.Finish();
}

struct DataBoxMetaRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DataBoxMetaRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_STEP_COUNT = 6,
    VT_VAR_COUNT = 8,
    VT_VAR_LEN = 10,
    VT_VLDESC = 12,
    VT_FILLED = 14
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int32_t step_count() const {
    return GetField<int32_t>(VT_STEP_COUNT, 0);
  }
  int32_t var_count() const {
    return GetField<int32_t>(VT_VAR_COUNT, 0);
  }
  int32_t var_len() const {
    return GetField<int32_t>(VT_VAR_LEN, 0);
  }
  const VLDescRequest *vldesc() const {
    return GetPointer<const VLDescRequest *>(VT_VLDESC);
  }
  bool filled() const {
    return GetField<uint8_t>(VT_FILLED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_STEP_COUNT, 4) &&
           VerifyField<int32_t>(verifier, VT_VAR_COUNT, 4) &&
           VerifyField<int32_t>(verifier, VT_VAR_LEN, 4) &&
           VerifyOffset(verifier, VT_VLDESC) &&
           verifier.VerifyTable(vldesc()) &&
           VerifyField<uint8_t>(verifier, VT_FILLED, 1) &&
           verifier.EndTable();
  }
};

struct DataBoxMetaRequestBuilder {
  typedef DataBoxMetaRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(DataBoxMetaRequest::VT_ID, id, 0);
  }
  void add_step_count(int32_t step_count) {
    fbb_.AddElement<int32_t>(DataBoxMetaRequest::VT_STEP_COUNT, step_count, 0);
  }
  void add_var_count(int32_t var_count) {
    fbb_.AddElement<int32_t>(DataBoxMetaRequest::VT_VAR_COUNT, var_count, 0);
  }
  void add_var_len(int32_t var_len) {
    fbb_.AddElement<int32_t>(DataBoxMetaRequest::VT_VAR_LEN, var_len, 0);
  }
  void add_vldesc(::flatbuffers::Offset<VLDescRequest> vldesc) {
    fbb_.AddOffset(DataBoxMetaRequest::VT_VLDESC, vldesc);
  }
  void add_filled(bool filled) {
    fbb_.AddElement<uint8_t>(DataBoxMetaRequest::VT_FILLED, static_cast<uint8_t>(filled), 0);
  }
  explicit DataBoxMetaRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DataBoxMetaRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DataBoxMetaRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DataBoxMetaRequest> CreateDataBoxMetaRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int32_t step_count = 0,
    int32_t var_count = 0,
    int32_t var_len = 0,
    ::flatbuffers::Offset<VLDescRequest> vldesc = 0,
    bool filled = false) {
  DataBoxMetaRequestBuilder builder_(_fbb);
  builder_.add_vldesc(vldesc);
  builder_.add_var_len(var_len);
  builder_.add_var_count(var_count);
  builder_.add_step_count(step_count);
  builder_.add_id(id);
  builder_.add_filled(filled);
  return builder_.Finish();
}

struct DBCreateReply FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBCreateReplyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DB_META = 4
  };
  const DataBoxMetaRequest *db_meta() const {
    return GetPointer<const DataBoxMetaRequest *>(VT_DB_META);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DB_META) &&
           verifier.VerifyTable(db_meta()) &&
           verifier.EndTable();
  }
};

struct DBCreateReplyBuilder {
  typedef DBCreateReply Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_db_meta(::flatbuffers::Offset<DataBoxMetaRequest> db_meta) {
    fbb_.AddOffset(DBCreateReply::VT_DB_META, db_meta);
  }
  explicit DBCreateReplyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBCreateReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBCreateReply>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBCreateReply> CreateDBCreateReply(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<DataBoxMetaRequest> db_meta = 0) {
  DBCreateReplyBuilder builder_(_fbb);
  builder_.add_db_meta(db_meta);
  return builder_.Finish();
}

struct DBgetRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBgetRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CNT_ID = 4,
    VT_TIMEOUT = 6
  };
  const ContentIDRequest *cnt_id() const {
    return GetPointer<const ContentIDRequest *>(VT_CNT_ID);
  }
  int64_t timeout() const {
    return GetField<int64_t>(VT_TIMEOUT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CNT_ID) &&
           verifier.VerifyTable(cnt_id()) &&
           VerifyField<int64_t>(verifier, VT_TIMEOUT, 8) &&
           verifier.EndTable();
  }
};

struct DBgetRequestBuilder {
  typedef DBgetRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cnt_id(::flatbuffers::Offset<ContentIDRequest> cnt_id) {
    fbb_.AddOffset(DBgetRequest::VT_CNT_ID, cnt_id);
  }
  void add_timeout(int64_t timeout) {
    fbb_.AddElement<int64_t>(DBgetRequest::VT_TIMEOUT, timeout, 0);
  }
  explicit DBgetRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBgetRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBgetRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBgetRequest> CreateDBgetRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ContentIDRequest> cnt_id = 0,
    int64_t timeout = 0) {
  DBgetRequestBuilder builder_(_fbb);
  builder_.add_timeout(timeout);
  builder_.add_cnt_id(cnt_id);
  return builder_.Finish();
}

struct DBgetReply FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBgetReplyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IP = 4,
    VT_PORT = 6
  };
  const ::flatbuffers::String *ip() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IP);
  }
  int32_t port() const {
    return GetField<int32_t>(VT_PORT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_IP) &&
           verifier.VerifyString(ip()) &&
           VerifyField<int32_t>(verifier, VT_PORT, 4) &&
           verifier.EndTable();
  }
};

struct DBgetReplyBuilder {
  typedef DBgetReply Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ip(::flatbuffers::Offset<::flatbuffers::String> ip) {
    fbb_.AddOffset(DBgetReply::VT_IP, ip);
  }
  void add_port(int32_t port) {
    fbb_.AddElement<int32_t>(DBgetReply::VT_PORT, port, 0);
  }
  explicit DBgetReplyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBgetReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBgetReply>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBgetReply> CreateDBgetReply(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> ip = 0,
    int32_t port = 0) {
  DBgetReplyBuilder builder_(_fbb);
  builder_.add_port(port);
  builder_.add_ip(ip);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DBgetReply> CreateDBgetReplyDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *ip = nullptr,
    int32_t port = 0) {
  auto ip__ = ip ? _fbb.CreateString(ip) : 0;
  return CreateDBgetReply(
      _fbb,
      ip__,
      port);
}

struct DBcontainRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBcontainRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CNT_ID = 4
  };
  const ContentIDRequest *cnt_id() const {
    return GetPointer<const ContentIDRequest *>(VT_CNT_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CNT_ID) &&
           verifier.VerifyTable(cnt_id()) &&
           verifier.EndTable();
  }
};

struct DBcontainRequestBuilder {
  typedef DBcontainRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cnt_id(::flatbuffers::Offset<ContentIDRequest> cnt_id) {
    fbb_.AddOffset(DBcontainRequest::VT_CNT_ID, cnt_id);
  }
  explicit DBcontainRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBcontainRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBcontainRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBcontainRequest> CreateDBcontainRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ContentIDRequest> cnt_id = 0) {
  DBcontainRequestBuilder builder_(_fbb);
  builder_.add_cnt_id(cnt_id);
  return builder_.Finish();
}

struct DBcontainReply FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBcontainReplyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_CONTAIN = 4
  };
  bool is_contain() const {
    return GetField<uint8_t>(VT_IS_CONTAIN, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_CONTAIN, 1) &&
           verifier.EndTable();
  }
};

struct DBcontainReplyBuilder {
  typedef DBcontainReply Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_is_contain(bool is_contain) {
    fbb_.AddElement<uint8_t>(DBcontainReply::VT_IS_CONTAIN, static_cast<uint8_t>(is_contain), 0);
  }
  explicit DBcontainReplyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBcontainReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBcontainReply>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBcontainReply> CreateDBcontainReply(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool is_contain = false) {
  DBcontainReplyBuilder builder_(_fbb);
  builder_.add_is_contain(is_contain);
  return builder_.Finish();
}

struct DBReleaseRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBReleaseRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CNT_ID = 4
  };
  const ContentIDRequest *cnt_id() const {
    return GetPointer<const ContentIDRequest *>(VT_CNT_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CNT_ID) &&
           verifier.VerifyTable(cnt_id()) &&
           verifier.EndTable();
  }
};

struct DBReleaseRequestBuilder {
  typedef DBReleaseRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cnt_id(::flatbuffers::Offset<ContentIDRequest> cnt_id) {
    fbb_.AddOffset(DBReleaseRequest::VT_CNT_ID, cnt_id);
  }
  explicit DBReleaseRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBReleaseRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBReleaseRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBReleaseRequest> CreateDBReleaseRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ContentIDRequest> cnt_id = 0) {
  DBReleaseRequestBuilder builder_(_fbb);
  builder_.add_cnt_id(cnt_id);
  return builder_.Finish();
}

struct DBReleaseReply FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBReleaseReplyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_RELEASE = 4
  };
  bool is_release() const {
    return GetField<uint8_t>(VT_IS_RELEASE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_RELEASE, 1) &&
           verifier.EndTable();
  }
};

struct DBReleaseReplyBuilder {
  typedef DBReleaseReply Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_is_release(bool is_release) {
    fbb_.AddElement<uint8_t>(DBReleaseReply::VT_IS_RELEASE, static_cast<uint8_t>(is_release), 0);
  }
  explicit DBReleaseReplyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBReleaseReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBReleaseReply>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBReleaseReply> CreateDBReleaseReply(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool is_release = false) {
  DBReleaseReplyBuilder builder_(_fbb);
  builder_.add_is_release(is_release);
  return builder_.Finish();
}

struct DBDeleteRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBDeleteRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CNT_ID = 4
  };
  const ContentIDRequest *cnt_id() const {
    return GetPointer<const ContentIDRequest *>(VT_CNT_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CNT_ID) &&
           verifier.VerifyTable(cnt_id()) &&
           verifier.EndTable();
  }
};

struct DBDeleteRequestBuilder {
  typedef DBDeleteRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cnt_id(::flatbuffers::Offset<ContentIDRequest> cnt_id) {
    fbb_.AddOffset(DBDeleteRequest::VT_CNT_ID, cnt_id);
  }
  explicit DBDeleteRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBDeleteRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBDeleteRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBDeleteRequest> CreateDBDeleteRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ContentIDRequest> cnt_id = 0) {
  DBDeleteRequestBuilder builder_(_fbb);
  builder_.add_cnt_id(cnt_id);
  return builder_.Finish();
}

struct DBDeleteReply FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBDeleteReplyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IS_DELETE = 4
  };
  bool is_delete() const {
    return GetField<uint8_t>(VT_IS_DELETE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_IS_DELETE, 1) &&
           verifier.EndTable();
  }
};

struct DBDeleteReplyBuilder {
  typedef DBDeleteReply Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_is_delete(bool is_delete) {
    fbb_.AddElement<uint8_t>(DBDeleteReply::VT_IS_DELETE, static_cast<uint8_t>(is_delete), 0);
  }
  explicit DBDeleteReplyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBDeleteReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBDeleteReply>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBDeleteReply> CreateDBDeleteReply(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool is_delete = false) {
  DBDeleteReplyBuilder builder_(_fbb);
  builder_.add_is_delete(is_delete);
  return builder_.Finish();
}

struct GetContentIDRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetContentIDRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DB_ID = 4
  };
  uint64_t db_id() const {
    return GetField<uint64_t>(VT_DB_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_DB_ID, 8) &&
           verifier.EndTable();
  }
};

struct GetContentIDRequestBuilder {
  typedef GetContentIDRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_db_id(uint64_t db_id) {
    fbb_.AddElement<uint64_t>(GetContentIDRequest::VT_DB_ID, db_id, 0);
  }
  explicit GetContentIDRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetContentIDRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetContentIDRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetContentIDRequest> CreateGetContentIDRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t db_id = 0) {
  GetContentIDRequestBuilder builder_(_fbb);
  builder_.add_db_id(db_id);
  return builder_.Finish();
}

struct GetContentIDReply FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GetContentIDReplyBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CNT_ID = 4
  };
  const ContentIDRequest *cnt_id() const {
    return GetPointer<const ContentIDRequest *>(VT_CNT_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_CNT_ID) &&
           verifier.VerifyTable(cnt_id()) &&
           verifier.EndTable();
  }
};

struct GetContentIDReplyBuilder {
  typedef GetContentIDReply Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_cnt_id(::flatbuffers::Offset<ContentIDRequest> cnt_id) {
    fbb_.AddOffset(GetContentIDReply::VT_CNT_ID, cnt_id);
  }
  explicit GetContentIDReplyBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GetContentIDReply> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GetContentIDReply>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GetContentIDReply> CreateGetContentIDReply(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<ContentIDRequest> cnt_id = 0) {
  GetContentIDReplyBuilder builder_(_fbb);
  builder_.add_cnt_id(cnt_id);
  return builder_.Finish();
}

#endif  // FLATBUFFERS_GENERATED_DBFLB_H_
