// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: index.proto
#ifndef GRPC_index_2eproto__INCLUDED
#define GRPC_index_2eproto__INCLUDED

#include "index.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace IndexRpc {

class indexService final {
 public:
  static constexpr char const* service_full_name() {
    return "IndexRpc.indexService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::IndexRpc::IndexReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndexRpc::IndexReply>> AsyncGetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndexRpc::IndexReply>>(AsyncGetIndexRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndexRpc::IndexReply>> PrepareAsyncGetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::IndexRpc::IndexReply>>(PrepareAsyncGetIndexRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::IndexRpc::IndexReply>* AsyncGetIndexRaw(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::IndexRpc::IndexReply>* PrepareAsyncGetIndexRaw(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::IndexRpc::IndexReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndexRpc::IndexReply>> AsyncGetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndexRpc::IndexReply>>(AsyncGetIndexRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndexRpc::IndexReply>> PrepareAsyncGetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::IndexRpc::IndexReply>>(PrepareAsyncGetIndexRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response, std::function<void(::grpc::Status)>) override;
      void GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::IndexRpc::IndexReply>* AsyncGetIndexRaw(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::IndexRpc::IndexReply>* PrepareAsyncGetIndexRaw(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetIndex_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetIndex(::grpc::ServerContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetIndex() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndex(::grpc::ServerContext* /*context*/, const ::IndexRpc::IndexSend* /*request*/, ::IndexRpc::IndexReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetIndex(::grpc::ServerContext* context, ::IndexRpc::IndexSend* request, ::grpc::ServerAsyncResponseWriter< ::IndexRpc::IndexReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetIndex<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetIndex() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::IndexRpc::IndexSend, ::IndexRpc::IndexReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response) { return this->GetIndex(context, request, response); }));}
    void SetMessageAllocatorFor_GetIndex(
        ::grpc::MessageAllocator< ::IndexRpc::IndexSend, ::IndexRpc::IndexReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::IndexRpc::IndexSend, ::IndexRpc::IndexReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndex(::grpc::ServerContext* /*context*/, const ::IndexRpc::IndexSend* /*request*/, ::IndexRpc::IndexReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetIndex(
      ::grpc::CallbackServerContext* /*context*/, const ::IndexRpc::IndexSend* /*request*/, ::IndexRpc::IndexReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetIndex<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetIndex() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndex(::grpc::ServerContext* /*context*/, const ::IndexRpc::IndexSend* /*request*/, ::IndexRpc::IndexReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetIndex() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndex(::grpc::ServerContext* /*context*/, const ::IndexRpc::IndexSend* /*request*/, ::IndexRpc::IndexReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetIndex(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetIndex() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetIndex(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetIndex(::grpc::ServerContext* /*context*/, const ::IndexRpc::IndexSend* /*request*/, ::IndexRpc::IndexReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetIndex(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetIndex : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetIndex() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::IndexRpc::IndexSend, ::IndexRpc::IndexReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::IndexRpc::IndexSend, ::IndexRpc::IndexReply>* streamer) {
                       return this->StreamedGetIndex(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetIndex() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetIndex(::grpc::ServerContext* /*context*/, const ::IndexRpc::IndexSend* /*request*/, ::IndexRpc::IndexReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetIndex(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::IndexRpc::IndexSend,::IndexRpc::IndexReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetIndex<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetIndex<Service > StreamedService;
};

}  // namespace IndexRpc


#endif  // GRPC_index_2eproto__INCLUDED
