// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: index.proto

#include "manager/proto/index.pb.h"
#include "manager/proto/index.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace IndexRpc {

static const char* indexService_method_names[] = {
  "/IndexRpc.indexService/GetIndex",
};

std::unique_ptr< indexService::Stub> indexService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< indexService::Stub> stub(new indexService::Stub(channel, options));
  return stub;
}

indexService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetIndex_(indexService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status indexService::Stub::GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::IndexRpc::IndexReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::IndexRpc::IndexSend, ::IndexRpc::IndexReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetIndex_, context, request, response);
}

void indexService::Stub::async::GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::IndexRpc::IndexSend, ::IndexRpc::IndexReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetIndex_, context, request, response, std::move(f));
}

void indexService::Stub::async::GetIndex(::grpc::ClientContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetIndex_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::IndexRpc::IndexReply>* indexService::Stub::PrepareAsyncGetIndexRaw(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::IndexRpc::IndexReply, ::IndexRpc::IndexSend, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetIndex_, context, request);
}

::grpc::ClientAsyncResponseReader< ::IndexRpc::IndexReply>* indexService::Stub::AsyncGetIndexRaw(::grpc::ClientContext* context, const ::IndexRpc::IndexSend& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetIndexRaw(context, request, cq);
  result->StartCall();
  return result;
}

indexService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      indexService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< indexService::Service, ::IndexRpc::IndexSend, ::IndexRpc::IndexReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](indexService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::IndexRpc::IndexSend* req,
             ::IndexRpc::IndexReply* resp) {
               return service->GetIndex(ctx, req, resp);
             }, this)));
}

indexService::Service::~Service() {
}

::grpc::Status indexService::Service::GetIndex(::grpc::ServerContext* context, const ::IndexRpc::IndexSend* request, ::IndexRpc::IndexReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace IndexRpc

